apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: file-demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: file-demo
    spec:
      containers:
      - name: file-demo
        image: gcr.io/omega-signifier-168912/filedemo/file-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
      imagePullSecrets:
        - name: gcr.io
