apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-file-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: my-file-demo
    spec:
      containers:
      - name: my-file-demo
        image: gcr.io/csd-automation/filedemo/file-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
      imagePullSecrets:
        - name: gcr.io
