apiVersion: v1
kind: Service
metadata:
  labels:
    name: my-file-demo-service
  name: my-file-demo-service
spec:
  type: LoadBalancer
  loadBalancerIP: 104.196.96.183
  ports:
    # The port that this service should serve on.
    - port: 9090
      targetPort: 9090
      protocol: TCP
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: "my-file-demo"
